# Generated by Django 4.0.4 on 2022-05-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_alter_country_options_alter_country_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time']},
        ),
        migrations.AlterModelOptions(
            name='flight_ticket',
            options={'ordering': ['flight']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='user_role',
            options={'ordering': ['role_name']},
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='Country_name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='Flag',
            new_name='flag',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Credit_card_no',
            new_name='credit_card_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Airline_id',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Departure_time',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Destination_country_id',
            new_name='destination_country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Landing_time',
            new_name='landing_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Origin_country_id',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Remaining_tickets',
            new_name='remaining_tickets',
        ),
        migrations.RenameField(
            model_name='flight_ticket',
            old_name='Customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='flight_ticket',
            old_name='Flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user_role',
            old_name='Role_name',
            new_name='role_name',
        ),
    ]
