# Generated by Django 4.0.4 on 2022-05-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0003_alter_administrator_options_alter_airline_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
